version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: wakanda_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql

  gestion_trafico:
    build:
      context: .
      dockerfile: gestion_trafico/Dockerfile
    container_name: ms_trafico
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=${DATABASE_URL_TRAFFIC}
    ports:
      - "8001:8000"

  gestion_energia:
    build:
      context: .
      dockerfile: gestion_energia/Dockerfile
    container_name: ms_energia
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=${DATABASE_URL_ENERGY}
    ports:
      - "8002:8000"

  gateway_api:
    build: ./gateway_api
    container_name: ms_gateway
    depends_on:
      - gestion_trafico
      - gestion_energia
    environment:
      - TRAFFIC_SERVICE_URL=http://gestion_trafico:8000
      - ENERGY_SERVICE_URL=http://gestion_energia:8000
    ports:
      - "8000:8000"

  gestion_agua:
    build:
      context: .
      dockerfile: gestion_agua/Dockerfile
    container_name: ms_agua
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=${DATABASE_URL_WATER}
    ports:
      - "8003:8000"

  gestion_vigilancia:
    build:
      context: .
      dockerfile: gestion_vigilancia/Dockerfile
    container_name: ms_seguridad
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=${DATABASE_URL_SECURITY}
    ports:
      - "8004:8000"

  gestion_residuos:
    build:
      context: .
      dockerfile: gestion_residuos/Dockerfile
    container_name: ms_residuos
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=${DATABASE_URL_WASTE}
    ports:
      - "8005:8000"