apiVersion: v1
kind: ConfigMap
metadata:
  name: wakanda-config
data:
  # Script SQL extraído de tu configuración
  init_databases.sql: |
    CREATE DATABASE traffic_db;
    CREATE DATABASE energy_db;
    CREATE DATABASE water_db;
    CREATE DATABASE security_db;
    CREATE DATABASE waste_db;
    CREATE DATABASE users_db;
---
apiVersion: v1
kind: Secret
metadata:
  name: wakanda-secrets
type: Opaque
stringData:
  # Credenciales de Base de Datos
  DB_USER: "admin"
  DB_PASSWORD: "admin"

  # Credenciales MinIO
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"

  # Claves de la aplicación
  SECRET_KEY: "123456"

  # Configuración de Correo
  MAIL_USERNAME: "uaxconcurrente@gmail.com"
  MAIL_PASSWORD: "mafntakzhzljzdxm"