apiVersion: v1
kind: ConfigMap
metadata:
  name: wakanda-config
data:
  # Script SQL extraído de tu archivo init_databases.sql
  init_databases.sql: |
    CREATE DATABASE traffic_db;
    CREATE DATABASE energy_db;
    CREATE DATABASE water_db;
    CREATE DATABASE security_db;
    CREATE DATABASE waste_db;
    CREATE DATABASE users_db;

  name: wakanda-secrets
---
type: Opaque
stringData:
  # Credenciales base
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  SECRET_KEY: "supersecreto_gratis"
  # Configuración de correo (ajusta con tus valores reales si los tienes)
  MAIL_USERNAME: "tu_correo@gmail.com"
  MAIL_PASSWORD: "tu_contraseña_app"