apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-cluster-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-cluster-binding
subjects:
  - kind: ServiceAccount
    name: gateway-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: gateway-cluster-role
  apiGroup: rbac.authorization.k8s.io